import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import vm from 'node:vm';
import * as timing from '../basketball/timing.js';
const elements = new Map();
const element = id => {
  if (!elements.has(id)) elements.set(id, {textContent:'',dataset:{},addEventListener(type,fn){this[type]=fn;},setAttribute(){},focus(){},getBoundingClientRect(){return {left:0,width:600};}});
  return elements.get(id);
};
const context2d = new Proxy({}, {get:(_,key)=> key.startsWith('create') ? ()=>({addColorStop(){}}) : ()=>{}});
element('court').getContext=()=>context2d;
const buttons = Array.from({length:4},(_,i)=>Object.assign(element(`player${i}`),{dataset:{shooter:i}}));
let clock=0, records=[], finishes=0;
const sandbox=vm.createContext({...timing,URLSearchParams,location:{search:'?team=vols'},Image:class {},localStorage:{getItem(){return null;},setItem(){}},performance:{now:()=>clock},requestAnimationFrame(){},document:{getElementById:element,querySelectorAll:()=>buttons,documentElement:{style:{setProperty(){}}}},leaderboard:()=>({async start(){records=[];return [0];},record(input){records.push(input);},finish(){finishes++;}})});
const source=(await readFile(new URL('../basketball/game.js',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'');
vm.runInContext(source,sandbox);
await new Promise(resolve=>setImmediate(resolve));
element('start-round').click();
for (const button of buttons) button.click();
assert.equal(records.length,4);
assert(buttons.every(button=>!button.disabled),'All shooters remain available');
clock=160;
for (const button of buttons) button.click();
assert.equal(records.length,8,'Eight balls launched before first one lands');
vm.runInContext('draw()',sandbox);
clock=2000; vm.runInContext('updateRound(performance.now()); draw()',sandbox);
assert.equal(vm.runInContext('shots',sandbox),8);
assert.equal(vm.runInContext('score',sandbox),timing.replayTiming([0],records).score);
clock=59999;
for (const button of buttons) button.click();
clock=60000; vm.runInContext('updateRound(performance.now()); draw()',sandbox);
assert.equal(finishes,0,'Wait for all buzzer beaters');
for (const button of buttons) button.click();
assert.equal(records.length,12,'No new shots at zero');
clock=61400; vm.runInContext('updateRound(performance.now()); draw()',sandbox);
assert.equal(finishes,1); assert.equal(vm.runInContext('shots',sandbox),12);
assert.equal(vm.runInContext('score',sandbox),timing.replayTiming([0],records).score);
await element('restart').click();
element('start-round').click();
element('court').pointerdown({isPrimary:false,pointerType:'touch',clientX:90,preventDefault(){}});
assert.equal(records.length,1,'Secondary touch can fire after reset');
assert.equal(vm.runInContext('balls.length',sandbox),1);
console.log('Passed: client concurrent shots, drawing, server score parity, buzzer drain, restart, and multitouch.');
